theme: jekyll-theme-minimal

title: Welcome to the Personal Website of Markus Wehr!
local: en_US

owner:
  name: Markus Wehr
  avatar: ![](image/headshot.png)
  bio: "This is my personal website."
  email: mwehr@uchicago.edu
  linkedin: markus-wehr
  github: markuswehr
  name: Markus Wehr
  
