title: Markus Wehr # your name (or website title) here
logo: <img src="images/headshot.jpg?raw=true" width="200" height="200"/> #"/images/headshot.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my personal website!<br>
  * *Education:* MSc Analytics; MSc Mgmt, Finance and Accounting<br>
  * *Experience:*3 1/2 years banking and consulting experience<br><br>
  * *Technical skills:* Python, R, Spark, Hadoop, Git, SQL, Google Cloud, Tableau, invision, Excel, PowerPoint<br>
  * *Languages:* Fluent in German and English<br>
  
  Please check out my website to learn more!
  
theme: jekyll-theme-minimal
google_analytics: UA-158041091-1 # your Google Analytics tracking ID here
