theme: jekyll-theme-minimal

title: Welcome to the Personal Website of Markus Wehr!
local: en_US

owner:
  name: Markus Wehr
  avatar: <img src="images/headshot_PNG.png" width="200" height="200">
  bio: "This is my personal website."
  email: mwehr@uchicago.edu
  linkedin: markus-wehr
  github: markuswehr
  name: Markus Wehr
  
